-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.USERS
(
    USR_ID_PK BIGINT NOT NULL,
    USR_NAME VARCHAR(50) NOT NULL,
    USR_SURNAME VARCHAR(50) NOT NULL,
    USR_EMAIL VARCHAR(100) NOT NULL,
    USR_ADDRESS VARCHAR(200) NOT NULL,
    HST_INS_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    HST_UPD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT USR_PK PRIMARY KEY (USR_ID_PK)
);
	
CREATE SEQUENCE IF NOT EXISTS public.SEQ_USERS AS BIGINT;